#!/bin/bash

#####################################################################
#        Some aliases only make sense to set if the required        #
#                      utility is installed                         #
#####################################################################
if [[ -x "$(command -v batcat -V)" || -x "$(command -v batcat -V)" ]]; then
	alias cat='batcat'
fi

if [[ -x "$(command -v xclipboard -version)" ]]; then
	alias xclipboard='xclip -selection clipboard'
fi

# Add an "alert" alias for long running commands
# Taken from the pop_os bashrc
alias alert='notify-send --urgency=normal -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#####################################################################
#        ls aliases                                                 #
#####################################################################
alias l='ls'
alias ll='ls -lha'

#####################################################################
#        typo-fixer aliases, append as needed                       #
#####################################################################
alias v='vim'
alias vmi='vim'
alias vvim='vim'

#####################################################################
#        aliases to make cd-stack simpler                           #
#####################################################################
alias s0='s 0'
alias s1='s 1'
alias s2='s 2'
alias s3='s 3'
alias s4='s 4'
alias s5='s 5'
alias s6='s 6'
alias s7='s 7'
alias s8='s 8'
alias s9='s 9'
alias s10='s 10'

#####################################################################
#        git shortcuts                                              #
#####################################################################
alias gs='git status'
alias ga='git add'
alias gp='git pull'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gd='git diff'
alias gl='git log'
