#!/bin/bash

if [[ -x "$(command -v batcat -V)" || -x "$(command -v batcat -V)" ]]; then
	alias cat='batcat'
fi

if [[ -x "$(command -v xclipboard -version)" ]]; then
	alias xclipboard='xclip -selection clipboard'
fi

# Add an "alert" alias for long running commands
# Taken from the pop_os bashrc
alias alert='notify-send --urgency=normal -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# ls aliases
alias l='ls'
alias ll='ls -lha'

# typo-fixer aliases, append as needed
alias vmi='vim'

# git shortcuts
alias gs='git status'
alias ga='git add'
alias gp='git pull'
alias gc='git commit -m'
