#!/bin/bash

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# Commands to ignore when appending to history
HISTIGNORE='clear:history:ls'

# Use neovim as default editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# Case-insensitive autocomplete
set completion-ignore-case on
